spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE} #run only job that i passed by parameter

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/house_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 9404JHKim@
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: mysql
  batch:
    jdbc:
      initialize-schema: always
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    service-key : pQ6sd7itmt%2F76%2FX8ca5otfWD9gdkKO6O1QstZX%2Bnit6EH7XfZ2fU0w79oSh993op%2FUUh4ASugray4s%2BLdL1tRA%3D%3D

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
